singleQuote: true
semi: false
printWidth: 80
tabWidth: 2
useTabs: false
trailingComma: es5
bracketSpacing: true
jsxSingleQuote: false
arrowParens: always
proseWrap: preserve
endOfLine: auto
embeddedLanguageFormatting: auto
plugins:
  - "prettier-plugin-tailwindcss"
